spring.application.name=mascota_virtual_back

# Configuració MongoDB
spring.data.mongodb.uri=${MONGO_URL}

# Habilita la creació automàtica d'índexs a MongoDB (nomUsuari)
spring.data.mongodb.auto-index-creation=true

# Configuració Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# JwtUtil Clave secreta
jwt.secret=${JWT_SECRET}

# JwtUtil Expiración en milisegundos (1 hora)
jwt.expiration=${JWT_EXPIRATION:3600000}

# Contraseña del usuario admin
admin.password=${ADMIN_PASSWORD}
