spring.application.name=mascota_virtual_back

# Configuracion MongoDB
spring.data.mongodb.uri=${MONGO_URL}

# Habilita la creacion automatica de indices a MongoDB (nomUsuari)
spring.data.mongodb.auto-index-creation=true

# Configuracion Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# JwtUtil Clave secreta
jwt.secret=${JWT_SECRET}

# JwtUtil Expiracion en milisegundos (1 hora)
jwt.expiration=${JWT_EXPIRATION:3600000}

# Contrasena del usuario admin
admin.password=${ADMIN_PASSWORD}